-- Create a sequence
CREATE SEQUENCE TDSS_TB_CASO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- DROP SEQUENCE TDSS_TB_CASO_SEQ;

-- Create the table with an auto-increment primary key
CREATE TABLE TDSS_TB_CASO (
	CD_CASO NUMBER (10) DEFAULT TDSS_TB_CASO_SEQ.NEXTVAL NOT NULL,
	NM_COMPLETO VARCHAR2 (100) NOT NULL,
	DS_EMAIL VARCHAR2 (100) NOT NULL,
	DS_MARCA VARCHAR2 (100) NOT NULL,
	DS_MODELO VARCHAR2 (100) NOT NULL,
	DS_IMAGEM VARCHAR2 (100) NOT NULL,
	DS_ENDERECO VARCHAR2 (100) NOT NULL,
	DT_CRIACAO DATE NOT NULL,
	DS_STATUS VARCHAR2 (100) NOT NULL,
	CONSTRAINT TDSS_TB_CASOS_PK PRIMARY KEY (CD_CASO)
);

-- Insert rows into TDSS_TB_CASO
INSERT INTO TDSS_TB_CASO (
	NM_COMPLETO,
	DS_EMAIL,
	DS_MARCA,
	DS_MODELO,
	DS_IMAGEM,
	DS_ENDERECO,
	DT_CRIACAO,
	DS_STATUS
) VALUES (
	'Augusto',
	'augustobb@live.com',
	'Fiat',
	'Uno',
	'https://www.google.com.br',
	'Rua 1',
	TO_DATE('2021-10-10', 'YYYY-MM-DD'),
	'ABERTO'
);

INSERT INTO TDSS_TB_CASO (
	NM_COMPLETO,
	DS_EMAIL,
	DS_MARCA,
	DS_MODELO,
	DS_IMAGEM,
	DS_ENDERECO,
	DT_CRIACAO,
	DS_STATUS
) VALUES (
	'Gutocebola',
	'gutocebola@gmail.com',
	'Tesla',
	'Model 3',
	'https://www.google.com.br',
	'Rua 2',
	TO_DATE('2022-10-10', 'YYYY-MM-DD'),
	'ABERTO'
);

DROP TABLE TDSS_TB_CASO;